version: "3"
services: 
    web:
      build: 
        context: .
        dockerfile: Dockerfile
      image: 042316/web
      ports:
        - 5000:5000
      environment: 
        - FLASK_ENV=development
    redis:
      image: redis:4.0.11-alpine